# Generated by Django 3.0.8 on 2020-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(choices=[('Sub-Saharan Africa', 'Sub-Saharan Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Middle East and North Africa', 'Middle East and North Africa'), ('Central America and the Caribbean', 'Central America and the Caribbean'), ('Australia and Oceania', 'Australia and Oceania'), ('North America', 'North America')], default='Asia', max_length=100, verbose_name='Region')),
                ('Country', models.CharField(max_length=100, verbose_name='Country')),
                ('Item_type', models.CharField(max_length=100, verbose_name='Item Type')),
                ('Sales_channel', models.CharField(max_length=100, verbose_name='Sales Channel')),
                ('Order_priority', models.CharField(max_length=30, verbose_name='Order Priority')),
                ('Order_date', models.CharField(max_length=30, verbose_name='Order Date')),
                ('Order_ID', models.IntegerField(null=True, verbose_name='Order ID')),
                ('Ship_date', models.CharField(max_length=30, verbose_name='Ship Date')),
                ('Units_sold', models.IntegerField(null=True, verbose_name='Units Sold')),
                ('Unit_price', models.FloatField(null=True, verbose_name='Units Price')),
                ('Unit_cost', models.FloatField(null=True, verbose_name='Unit Cost')),
                ('Total_revenue', models.FloatField(null=True, verbose_name='Total Revenue')),
                ('Total_cost', models.FloatField(null=True, verbose_name='Total Cost')),
                ('Total_profit', models.FloatField(null=True, verbose_name='Total Profit')),
            ],
        ),
    ]
